api_platform:
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
        
        # Validation exception
        ApiPlatform\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        
        # Custom mapping
        App\Exception\ClientAlreadyExistsException: 409
        App\Exception\UserAlreadyExistsException: 409
        App\Exception\NotLoggedInException: 401
        App\Exception\TimeTrackingNotFoundException: 404
        App\Exception\UserNotFoundException: 404
        App\Exception\UserConflictException: 409
        App\Exception\NoAdminException: 401
        App\Exception\InvalidTimeConfigException: 403
        App\Exception\ConfigBlankException: 403
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
